name: compile-test

# controls when workflow will run
on:
  # triggers the workflow on push or pull request events
  push:
  pull_request:
  
  # allows you to run this workflow manually from the actions tab on github
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up OpenJDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Compile Java source code and tests
        working-directory: ./Projects/P1
        run: javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
