name: compile-test

# controls when workflow will run
on:
  # triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # allows you to run this workflow manually from the actions tab on github
  workflow_dispatch:

jobs:
  build:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
      - name: Compile Java source code and tests
        working-directory: ./Projects/P1
        with:
          distribution: "zulu"
          java-version: "17"
      - run: javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
